-- Test: Trade Agreement Manager
-- Run with: bash tools/test.sh tests/diplomacy/agreement_manager_test.lua

dofile("tests/mocks/avorion.lua")

describe("AgreementManager", function()
    local AgreementManager
    local store

    before_each(function()
        _resetMocks()
        AgreementManager = include("diplomacy/agreement_manager")
        store = Server()
    end)

    describe("clampDiscount", function()
        it("returns default for nil", function()
            assert.are.equal(0.10, AgreementManager.clampDiscount(nil))
        end)

        it("clamps below minimum", function()
            assert.are.equal(0.01, AgreementManager.clampDiscount(0.001))
        end)

        it("clamps above maximum", function()
            assert.are.equal(0.30, AgreementManager.clampDiscount(0.50))
        end)

        it("passes through valid discount", function()
            assert.are.equal(0.15, AgreementManager.clampDiscount(0.15))
        end)
    end)

    describe("propose", function()
        it("creates a proposal", function()
            local ok, err = AgreementManager.propose(store, 1, 2, 0.10, 0.15, 1000)
            assert.is_true(ok)
            assert.is_nil(err)
        end)

        it("proposal is retrievable", function()
            AgreementManager.propose(store, 1, 2, 0.10, 0.15, 1000)
            local p = AgreementManager.getProposal(store, 1, 2)
            assert.is_not_nil(p)
            assert.are.equal(1, p.proposer)
            assert.are.equal(2, p.target)
            assert.are.equal(0.10, p.proposer_discount)
            assert.are.equal(0.15, p.target_discount)
            assert.are.equal("proposed", p.status)
        end)

        it("fails for self-agreement", function()
            local ok, err = AgreementManager.propose(store, 1, 1, 0.10, 0.10, 1000)
            assert.is_false(ok)
            assert.are.equal("Cannot propose agreement with yourself", err)
        end)

        it("fails when active agreement already exists", function()
            AgreementManager.propose(store, 1, 2, 0.10, 0.10, 1000)
            AgreementManager.accept(store, 1, 2, 2000)
            local ok, err = AgreementManager.propose(store, 1, 2, 0.20, 0.20, 3000)
            assert.is_false(ok)
            assert.are.equal("Active agreement already exists", err)
        end)

        it("fails when duplicate proposal exists", function()
            AgreementManager.propose(store, 1, 2, 0.10, 0.10, 1000)
            local ok, err = AgreementManager.propose(store, 1, 2, 0.20, 0.20, 2000)
            assert.is_false(ok)
            assert.are.equal("Pending proposal already exists", err)
        end)

        it("fails when reverse proposal exists", function()
            AgreementManager.propose(store, 2, 1, 0.10, 0.10, 1000)
            local ok, err = AgreementManager.propose(store, 1, 2, 0.20, 0.20, 2000)
            assert.is_false(ok)
            assert.are.equal("Pending proposal already exists from target", err)
        end)

        it("clamps discount rates", function()
            AgreementManager.propose(store, 1, 2, 0.99, 0.001, 1000)
            local p = AgreementManager.getProposal(store, 1, 2)
            assert.are.equal(0.30, p.proposer_discount)
            assert.are.equal(0.01, p.target_discount)
        end)
    end)

    describe("accept", function()
        it("creates active agreement from proposal", function()
            AgreementManager.propose(store, 1, 2, 0.10, 0.15, 1000)
            local ok, err = AgreementManager.accept(store, 1, 2, 2000)
            assert.is_true(ok)
            assert.is_nil(err)
        end)

        it("active agreement is retrievable", function()
            AgreementManager.propose(store, 1, 2, 0.10, 0.15, 1000)
            AgreementManager.accept(store, 1, 2, 2000)
            local a = AgreementManager.getActive(store, 1, 2)
            assert.is_not_nil(a)
            assert.are.equal("active", a.status)
            assert.are.equal(2000, a.accepted_at)
        end)

        it("active agreement is order-independent", function()
            AgreementManager.propose(store, 1, 2, 0.10, 0.15, 1000)
            AgreementManager.accept(store, 1, 2, 2000)
            local a = AgreementManager.getActive(store, 2, 1)
            assert.is_not_nil(a)
        end)

        it("removes the proposal after accepting", function()
            AgreementManager.propose(store, 1, 2, 0.10, 0.15, 1000)
            AgreementManager.accept(store, 1, 2, 2000)
            assert.is_nil(AgreementManager.getProposal(store, 1, 2))
        end)

        it("fails when no proposal exists", function()
            local ok, err = AgreementManager.accept(store, 1, 2, 1000)
            assert.is_false(ok)
            assert.are.equal("No pending proposal found", err)
        end)

        it("adds to active index", function()
            AgreementManager.propose(store, 1, 2, 0.10, 0.15, 1000)
            AgreementManager.accept(store, 1, 2, 2000)
            local active = AgreementManager.getAllActive(store)
            assert.are.equal(1, #active)
        end)
    end)

    describe("decline", function()
        it("removes proposal", function()
            AgreementManager.propose(store, 1, 2, 0.10, 0.15, 1000)
            local ok = AgreementManager.decline(store, 1, 2)
            assert.is_true(ok)
            assert.is_nil(AgreementManager.getProposal(store, 1, 2))
        end)

        it("returns false for non-existent proposal", function()
            assert.is_false(AgreementManager.decline(store, 1, 2))
        end)
    end)

    describe("getDiscount", function()
        it("returns 0 when no agreement exists", function()
            assert.are.equal(0, AgreementManager.getDiscount(store, 1, 2))
        end)

        it("returns correct asymmetric discount", function()
            -- Faction 1 offers 10% to Faction 2, requests 15% from Faction 2
            AgreementManager.propose(store, 1, 2, 0.10, 0.15, 1000)
            AgreementManager.accept(store, 1, 2, 2000)

            -- Faction 2 buying from Faction 1 gets 10% (what Faction 1 gives)
            local discount_for_2 = AgreementManager.getDiscount(store, 2, 1)
            assert.are.equal(0.10, discount_for_2)

            -- Faction 1 buying from Faction 2 gets 15% (what Faction 2 gives)
            local discount_for_1 = AgreementManager.getDiscount(store, 1, 2)
            assert.are.equal(0.15, discount_for_1)
        end)
    end)

    describe("calculateDiscount", function()
        it("returns original price when no agreement", function()
            local price, rate = AgreementManager.calculateDiscount(store, 1, 2, 10000)
            assert.are.equal(10000, price)
            assert.are.equal(0, rate)
        end)

        it("applies discount correctly", function()
            AgreementManager.propose(store, 1, 2, 0.10, 0.15, 1000)
            AgreementManager.accept(store, 1, 2, 2000)
            -- Faction 1 buys from Faction 2, gets 15% off
            local price, rate = AgreementManager.calculateDiscount(store, 1, 2, 10000)
            assert.are.equal(8500, price)
            assert.are.equal(0.15, rate)
        end)
    end)

    describe("cancel", function()
        it("removes active agreement", function()
            AgreementManager.propose(store, 1, 2, 0.10, 0.15, 1000)
            AgreementManager.accept(store, 1, 2, 2000)
            local ok = AgreementManager.cancel(store, 1, 2)
            assert.is_true(ok)
            assert.is_nil(AgreementManager.getActive(store, 1, 2))
        end)

        it("is order-independent", function()
            AgreementManager.propose(store, 1, 2, 0.10, 0.15, 1000)
            AgreementManager.accept(store, 1, 2, 2000)
            local ok = AgreementManager.cancel(store, 2, 1)
            assert.is_true(ok)
            assert.is_nil(AgreementManager.getActive(store, 1, 2))
        end)

        it("returns false for non-existent agreement", function()
            assert.is_false(AgreementManager.cancel(store, 1, 2))
        end)

        it("removes from active index", function()
            AgreementManager.propose(store, 1, 2, 0.10, 0.15, 1000)
            AgreementManager.accept(store, 1, 2, 2000)
            AgreementManager.cancel(store, 1, 2)
            assert.are.equal(0, #AgreementManager.getAllActive(store))
        end)
    end)

    describe("getAllActive / getAllProposals", function()
        it("tracks multiple agreements and proposals", function()
            AgreementManager.propose(store, 1, 2, 0.10, 0.10, 1000)
            AgreementManager.accept(store, 1, 2, 2000)
            AgreementManager.propose(store, 3, 4, 0.10, 0.10, 1000)
            AgreementManager.accept(store, 3, 4, 2000)
            AgreementManager.propose(store, 5, 6, 0.10, 0.10, 1000)

            assert.are.equal(2, #AgreementManager.getAllActive(store))
            assert.are.equal(1, #AgreementManager.getAllProposals(store))
        end)
    end)
end)
